version: '3.7'

services:         
    bridge-mode-app:
        build:
           context: .
           dockerfile: Dockerfile
        ports:
          - "8080:8080"
          - "127.0.0.1:8089:8080"
        # brigde network = NAT network. lay Docker0 của Host network = gateway
        #  co the connect ra ngoai LAN, internet qua gateway  
        network_mode: "bridge"
        #network_mode: "host"   
 