version: '3.7'

services:         
    bridge-network-app1:
        build:
           context: .
           dockerfile: Dockerfile
        ports:
          - "8081:8080"
        networks: 
            bridge-external-network:
                 ipv4_address: 188.188.1.11 
                 
    bridge-network-app2: 
        build:
           context: .
           dockerfile: Dockerfile
        ports:
          - "8082:8080"
        networks: 
            bridge-external-network:
                 ipv4_address: 188.188.1.12               
                  

networks:             
    bridge-external-network:            
        driver: bridge      
        # true: no-internet. no LAN connect, can not connect to Host Machine
        internal: true     
        ipam:
            driver: default
            config:
                - subnet: 188.188.1.0/24   
